# This file was generated by GoReleaser. DO NOT EDIT.
cask "unmute" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr",
          args: ["-dr", "com.apple.quarantine", "unmute"],
          chdir: "."
    end
  end

  version "0.5.6"

  on_macos do
    on_arm do
      sha256 "74d64dbc926b5ba20ae222f4ad2e2fa300474f2511979521c1a44d94f0249a9f"
      url "https://github.com/slng-ai/unmute/releases/download/v#{version}/unmute_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "821585c9f4477ce2c76e8338d3c25f0f75ea1af602b7f32a24e7787d33098af2"
      url "https://github.com/slng-ai/unmute/releases/download/v#{version}/unmute_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f4840dbab5941c3f3e920f6498105cf4adcd7f52b63fb30c16b1d7993a891e8c"
      url "https://github.com/slng-ai/unmute/releases/download/v#{version}/unmute_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f38b711210d2a85fd61e26177ffd4e728ef04b1171dfe6c5d0e6b19eefdc20db"
      url "https://github.com/slng-ai/unmute/releases/download/v#{version}/unmute_#{version}_linux_amd64.tar.gz"
    end
  end

  name "unmute"
  desc "Compile a declarative voice-agent package to Pipecat or LiveKit"
  homepage "https://github.com/slng-ai/unmute"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "unmute"

  # No zap stanza required
end
