# This file was generated by GoReleaser. DO NOT EDIT.
cask "unmute" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "69158a794e3645c18b2fbd20bde30253cf33de76b1358457d9b2c1dcf2a9be0c"
      url "https://github.com/slng-ai/unmute/releases/download/v#{version}/unmute_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9f43baf777a045c6ab4afb154636d139a6b453cd7f251b5c35a4047677a13576"
      url "https://github.com/slng-ai/unmute/releases/download/v#{version}/unmute_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "02ec08d01b69284b056dc62c4a2830bdf2f058be5a1b52803c955d827da4f1d9"
      url "https://github.com/slng-ai/unmute/releases/download/v#{version}/unmute_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "95a7beab66e351a60693614517cef74d4bf0ced35c33a192d2dbe189db8502f4"
      url "https://github.com/slng-ai/unmute/releases/download/v#{version}/unmute_#{version}_linux_amd64.tar.gz"
    end
  end

  name "unmute"
  desc "Compile a declarative voice-agent package to Pipecat or LiveKit"
  homepage "https://github.com/slng-ai/unmute"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "unmute"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/unmute"]
    end
  end

  # No zap stanza required
end
