# This file was generated by GoReleaser. DO NOT EDIT.
cask "unmute" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr",
          args: ["-dr", "com.apple.quarantine", "unmute"],
          chdir: "."
    end
  end

  version "0.7.1"

  on_macos do
    on_arm do
      sha256 "4067db2a9d4d185c30756e9fb01394c40432156c9bf07d115dcce2cbcd8ff8df"
      url "https://github.com/slng-ai/unmute/releases/download/v#{version}/unmute_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "726000cea7b136e919df7674ef799e270e01731ff43be38cb9acc71b54e37013"
      url "https://github.com/slng-ai/unmute/releases/download/v#{version}/unmute_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6a4ce3146acef17cca75b0827b067ca1ee83c605f78c67069d996a8b388870be"
      url "https://github.com/slng-ai/unmute/releases/download/v#{version}/unmute_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d2e88bd0bfa3d10157319d9ac292dffd7b5c303d8969873dfd688d9148f6de5e"
      url "https://github.com/slng-ai/unmute/releases/download/v#{version}/unmute_#{version}_linux_amd64.tar.gz"
    end
  end

  name "unmute"
  desc "Compile a declarative voice-agent package to Pipecat or LiveKit"
  homepage "https://github.com/slng-ai/unmute"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "unmute"

  # No zap stanza required
end
